### PR TITLE
Added link to CMS Plugin documentation page

### PR DESCRIPTION
**Pull request by skleinfeldt**
@witekdev @alecpm I discovered Siteimprove has a helpful page about how their plugin works, so I added it to the README.

@alecpm could you please review, merge, and release once again. Sorry for the trouble and no rush.

### CODE REVIEW

**Comment by skleinfeldt** [comment]
@witekdev or @alecpm sorry for the bother but could one of you please review and merge this PR (for a minor doc fix) and make another release? (Going to give a lightning talk on this tomorrow.)

**Review by hvelarde — APPROVED** [review]
LGTM

**Comment by witekdev** [comment]
Master is ready for @alecpm to push 1.0.3 to PYPI

**Comment by witekdev** [comment]
@skleinfeldt Alec just made a release, happy lightning talk :)

**Comment by skleinfeldt** [comment]
:-) Thanks everyone :-)

**Pull request merged**
